config/routes.rb
Rails.application.routes.draw do
  
  # resources :leads
  post 'leads', to: 'leads#create'
  resources :quotes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'home#index'
  get '/residential', to: 'home#residential'
  get '/commercial', to: 'home#commercial'
  get '/quote', to: 'home#quote'
  get '/geo', to: 'home#geo'
  mount Blazer::Engine, at: "blazer"
  # get '/intervention', to: 'home#interventions'
  get '/interventions', to: 'interventions#new'
  post '/interventions', to: 'interventions#create'

  get 'interventions/update_buildings' => 'interventions#update_buildings'
  get 'interventions/update_batteries' => 'interventions#update_batteries'
  get 'interventions/update_columns' => 'interventions#update_columns'
  get 'interventions/update_elevators' => 'interventions#update_elevators'
  get 'interventions/update_employees' => 'interventions#update_employees'

 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/quote.rb
class Quote < ApplicationRecord
    #Create a ticket with attachments.
    require 'rubygems'
    require 'rest_client'
    require 'json'
    # after_create :QuoteTickets

    def QuoteTickets

        # Your freshdesk domain
        freshdesk_domain = 'rocketelevators-help'

        # It could be either your user name or api_key.
        user_name_or_api_key = ENV["FRESHDESK_API_KEY"]

        # If you have given api_key, then it should be x. If you have given user name, it should be password
        password_or_x = 'X'

        json_payload = {
                        unique_external_id: "#{id}",
                        status: 2,            
                        priority: 1,
                        type: "Feature Request",
                        description: "The contact #{full_name_of_the_contact} from company #{company_name} can be reached at email #{email}. A quote as been created and is containing #{elevator_amount} elevators. The building has #{number_of_floors} floors and #{number_of_basements} basements. This would require contribution from Rocket Elevators.",
                        subject: "#{full_name_of_the_contact} from #{company_name}"}.to_json

        freshdesk_api_path = 'api/v2/tickets'

        freshdesk_api_url  = "https://#{freshdesk_domain}.freshdesk.com/#{freshdesk_api_path}"

        site = RestClient::Resource.new(freshdesk_api_url, user_name_or_api_key, password_or_x)

        begin
        response = site.post(json_payload, :content_type=>'application/json')
        puts "response_code: #{response.code} \n Location Header: #{response.headers[:location]}\n response_body: #{response.body}"
        rescue RestClient::Exception => exception
        puts 'API Error: Your request is not successful. If you are not able to debug this error properly, mail us at support@freshdesk.com with the follwing X-Request-Id'
        puts "X-Request-Id : #{exception.response.headers[:x_request_id]}"
        puts "Response Code: #{exception.response.code} Response Body: #{exception.response.body} "
        end
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
 
  protect_from_forgery with: :null_session
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)
    respond_to do |format|
      if @quote.save
        format.html { redirect_to(root_path, :notice => "Your quote was successfully sent!")}
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      
      params.require(:quote).permit(:buildingType, :number_of_floors, :number_of_basements, :number_of_apartments, :number_of_parking_spots, :elevator_amount, :number_of_companies, :maximum_occupancy, :number_of_corporations, :business_hours, :range, :company_name, :email)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote) do |form| %>
  <% if quote.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
        <% quote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type %>
  </div>

  <div>
    <%= form.label :number_of_floors, style: "display: block" %>
    <%= form.number_field :number_of_floors %>
  </div>

  <div>
    <%= form.label :number_of_basements, style: "display: block" %>
    <%= form.number_field :number_of_basements %>
  </div>

  <div>
    <%= form.label :number_of_apartments, style: "display: block" %>
    <%= form.number_field :number_of_apartments %>
  </div>

  <div>
    <%= form.label :number_of_parking_spots, style: "display: block" %>
    <%= form.number_field :number_of_parking_spots %>
  </div>

  <div>
    <%= form.label :number_of_elevators, style: "display: block" %>
    <%= form.number_field :number_of_elevators %>
  </div>

  <div>
    <%= form.label :number_of_companies, style: "display: block" %>
    <%= form.number_field :number_of_companies %>
  </div>

  <div>
    <%= form.label :maximum_occupancy, style: "display: block" %>
    <%= form.number_field :maximum_occupancy %>
  </div>

  <div>
    <%= form.label :number_of_corporations, style: "display: block" %>
    <%= form.number_field :number_of_corporations %>
  </div>

  <div>
    <%= form.label :business_hours, style: "display: block" %>
    <%= form.number_field :business_hours %>
  </div>

  <div>
    <%= form.label :standard, style: "display: block" %>
    <%= form.text_field :standard %>
  </div>

  <div>
    <%= form.label :premium, style: "display: block" %>
    <%= form.text_field :premium %>
  </div>

  <div>
    <%= form.label :excelium, style: "display: block" %>
    <%= form.text_field :excelium %>
  </div>

   <div>
    <%= form.label :company_name, style: "display: block" %>
    <%= form.text_field :company_name %>
  </div>

   <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

<% end %>

app/views/quotes/_quote.html.erb
<div id="<%= dom_id quote %>">
  <p>
      <strong>Type:</strong>
      <%= quote.buildingType %>
  </p>

  <p>
    <strong>Number_of_floors:</strong>
    <%= quote.number_of_floors %>
  </p>

  <p>
    <strong>Number_of_basements:</strong>
    <%= quote.number_of_basements %>
  </p>

  <p>
    <strong>Number_of_apartments:</strong>
    <%= quote.number_of_apartments %>
  </p>

  <p>
    <strong>Number_of_parking_spots:</strong>
    <%= quote.number_of_parking_spots %>
  </p>

  <p>
    <strong>Number_of_elevators:</strong>
    <%= quote.number_of_elevators %>
  </p>

  <p>
    <strong>Number_of_companies:</strong>
    <%= quote.number_of_companies %>
  </p>

  <p>
    <strong>Maximum_occupancy:</strong>
    <%= quote.maximum_occupancy %>
  </p>

  <p>
    <strong>Number_of_corporations:</strong>
    <%= quote.number_of_corporations %>
  </p>

  <p>
    <strong>Business_hours:</strong>
    <%= quote.business_hours %>
  </p>
</div>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render "form", quote: @quote %>

<br>

<div>
  <%= link_to "Show this quote", @quote %> |
  <%= link_to "Back to quotes", quotes_path %>
</div>

app/views/quotes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Quotes</h1>

<div id="quotes">
  <% @quotes.each do |quote| %>
    <%= render quote %>
    <p>
      <%= link_to "Show this quote", quote %>
    </p>
  <% end %>
</div>

<%= link_to "New quote", new_quote_path %>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render "form", quote: @quote %>

<br>

<div>
  <%= link_to "Back to quotes", quotes_path %>
</div>

app/views/quotes/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @quote %>
<div>
  <%= link_to "Edit this quote", edit_quote_path(@quote) %> |
  <%= link_to "Back to quotes", quotes_path %>

  <%= button_to "Destroy this quote", @quote, method: :delete %>
</div>