config/routes.rb
Rails.application.routes.draw do
  
  # resources :leads
  post 'leads', to: 'leads#create'
  resources :quotes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'home#index'
  get '/residential', to: 'home#residential'
  get '/commercial', to: 'home#commercial'
  get '/quote', to: 'home#quote'
  get '/geo', to: 'home#geo'
  mount Blazer::Engine, at: "blazer"
  # get '/intervention', to: 'home#interventions'
  get '/interventions', to: 'interventions#new'
  post '/interventions', to: 'interventions#create'

  get 'interventions/update_buildings' => 'interventions#update_buildings'
  get 'interventions/update_batteries' => 'interventions#update_batteries'
  get 'interventions/update_columns' => 'interventions#update_columns'
  get 'interventions/update_elevators' => 'interventions#update_elevators'
  get 'interventions/update_employees' => 'interventions#update_employees'

 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/lead.rb
class Lead < ApplicationRecord
    #Create a ticket with attachments.
    require 'rubygems'
    require 'rest_client'
    require 'json'
    # after_create :LeadTickets
    def LeadTickets
        freshdesk_domain = 'rocketelevators-help'

        # It could be either your user name or api_key.
        user_name_or_api_key = ENV["FRESHDESK_API_KEY"]

        # If you have given api_key, then it should be x. If you have given user name, it should be password
        password_or_x = 'X'

        #attachments should be of the form array of Hash with files mapped to the key 'resource'.
    
        File.open(attachment_file_name, 'wb') do |f|
            f.write attached_file_stored_as_a_binary_file
        end
        
    
        json_payload = { 
                        status: 2,
                        unique_external_id: "#{id}",
                        priority: 1,
                        type: "Question",
                        description: "The contact #{full_name_of_the_contact} from company #{company_name} can be reached at email #{e_mail} and at phone number #{phone}. #{department_in_charge_of_the_elevators} has a project named #{project_name} which would require contribution from Rocket Elevators. \n #{project_description}",
                        subject: "#{full_name_of_the_contact} from #{company_name}",
                        attachments: [File.new(attachment_file_name, 'rb')]}
    
        File.delete(attachment_file_name) if File.exist?(attachment_file_name)
        
        freshdesk_api_path = 'api/v2/tickets'
        
        
        freshdesk_api_url  = "https://#{freshdesk_domain}.freshdesk.com/#{freshdesk_api_path}"

        site = RestClient::Resource.new(freshdesk_api_url, user_name_or_api_key, password_or_x)

        begin
        response = site.post(json_payload)
        puts "response_code: #{response.code} \nLocation Header: #{response.headers[:Location]} \nresponse_body: #{response.body} \n"
        rescue RestClient::Exception => exception
        puts 'API Error: Your request is not successful. If you are not able to debug this error properly, mail us at support@freshdesk.com with the follwing X-Request-Id'
        puts "X-Request-Id : #{exception.response.headers[:x_request_id]}"
        puts "Response Code: #{exception.response.code} \nResponse Body: #{exception.response.body} \n"
        end
    end
    require 'sendgrid-ruby'
    include SendGrid
    after_create :SENDGRID_API_KEY
   
    def SENDGRID_API_KEY
        lead = Lead.last
        fullName = lead.full_name_of_the_contact
        projectName = lead.project_name
        email = lead.e_mail

        mail = Mail.new
        mail.from = Email.new(email: 'codeboxx.h22@gmail.com')
        personalization = Personalization.new
        personalization.add_to(Email.new(email: email))
        personalization.add_dynamic_template_data({
            "subject" => "Thanks for contacting us",
            "fullName" => fullName,
            "projectName" => projectName,
            "email" => email
        })
        mail.add_personalization(personalization)
        mail.template_id = 'd-9e50f25cb38f4219889970b77111903c'

        sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
        begin
            response = sg.client.mail._("send").post(request_body: mail.to_json)
        rescue Exception => e
            puts e.message
        end
    end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: %i[ show edit update destroy ]

 
 
  # redirect_to login_path, info: "invaled emid"
  # POST /leads or /leads.json
  def create
    @lead = Lead.new(lead_params)

    if @lead.attached_file_stored_as_a_binary_file != nil
        @lead.attachment_file_name = @lead.attached_file_stored_as_a_binary_file.original_filename
        @lead.attached_file_stored_as_a_binary_file = @lead.attached_file_stored_as_a_binary_file.read   
    end
 
    respond_to do |format|
      if @lead.save
        format.html { redirect_to(root_path, :notice => "Your message was successfully sent!")}
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lead_params
      params.require(:lead).permit(:full_name_of_the_contact, :company_name, :e_mail, :phone, :project_name, :project_description, :department_in_charge_of_the_elevators, :message, :attached_file_stored_as_a_binary_file, :attachment_file_name)
    end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/leads/_form.html.erb
<%= form_with(model: lead) do |form| %>
  <% if lead.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
        <% lead.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :full_name_of_the_contact, style: "display: block" %>
    <%= form.text_field :full_name_of_the_contact %>
  </div>

  <div>
    <%= form.label :company_name, style: "display: block" %>
    <%= form.text_field :company_name %>
  </div>

  <div>
    <%= form.label :e_mail, style: "display: block" %>
    <%= form.text_field :e_mail %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :project_name, style: "display: block" %>
    <%= form.text_field :project_name %>
  </div>

  <div>
    <%= form.label :project_description, style: "display: block" %>
    <%= form.text_area :project_description %>
  </div>

  <div>
    <%= form.label :department_in_charge_of_the_elevators, style: "display: block" %>
    <%= form.select (:department_in_charge_of_the_elevators, Lead: :department_list) %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_area :message %>
  </div>

  <div>
    <%= form.label :attached_file_stored_as_a_binary_file, style: "display: block" %>
    <%= form.text_area :attached_file_stored_as_a_binary_file %>
  </div>

  <div>
    <%= form.label :date_of_the_contact_request, style: "display: block" %>
    <%= form.date_field :date_of_the_contact_request %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<h1>Editing lead</h1>

<%= render "form", lead: @lead %>

<br>

<div>
  <%= link_to "Show this lead", @lead %> |
  <%= link_to "Back to leads", leads_path %>
</div>

app/views/leads/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Leads</h1>

<div id="leads">
  <% @leads.each do |lead| %>
    <%= render lead %>
    <p>
      <%= link_to "Show this lead", lead %>
    </p>
  <% end %>
</div>

<%= link_to "New lead", new_lead_path %>

app/views/leads/new.html.erb
<h1>New lead</h1>

<%= render "form", lead: @lead %>

<br>

<div>
  <%= link_to "Back to leads", leads_path %>
</div>

app/views/leads/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @lead %>

<div>
  <%= link_to "Edit this lead", edit_lead_path(@lead) %> |
  <%= link_to "Back to leads", leads_path %>

  <%= button_to "Destroy this lead", @lead, method: :delete %>
</div>