config/routes.rb
Rails.application.routes.draw do
  
  # resources :leads
  post 'leads', to: 'leads#create'
  resources :quotes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'home#index'
  get '/residential', to: 'home#residential'
  get '/commercial', to: 'home#commercial'
  get '/quote', to: 'home#quote'
  get '/geo', to: 'home#geo'
  mount Blazer::Engine, at: "blazer"
  # get '/intervention', to: 'home#interventions'
  get '/interventions', to: 'interventions#new'
  post '/interventions', to: 'interventions#create'

  get 'interventions/update_buildings' => 'interventions#update_buildings'
  get 'interventions/update_batteries' => 'interventions#update_batteries'
  get 'interventions/update_columns' => 'interventions#update_columns'
  get 'interventions/update_elevators' => 'interventions#update_elevators'
  get 'interventions/update_employees' => 'interventions#update_employees'

 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/intervention.rb
class Intervention < ApplicationRecord
    belongs_to :customer
    belongs_to :building
    belongs_to :battery
    belongs_to :column, optional: true
    belongs_to :elevator, optional: true
    belongs_to :employee, optional: true
    belongs_to :author, class_name: 'Employee'
    
    #Create a ticket with attachments.
    require 'rubygems'
    require 'rest_client'
    require 'json'
    after_create :interventionTickets

    def interventionTickets
        ## == PaperTrail ==
        # config.audit_with :paper_trail, 'User', 'PaperTrail::Version' # PaperTrail >= 3.0.0
        # Your freshdesk domain
        freshdesk_domain = 'rocketelevators-supportdesk'
    
        # It could be either your user name or api_key.
        user_name_or_api_key = ENV["FRESHDESK_API_KEY"]

        # If you have given api_key, then it should be x. If you have given user name, it should be password
        password_or_x = 'X'
        
        column_id = self.column_id == nil ? "n/a" : self.column_id
        elevator_id = self.elevator_id == nil ? "n/a" : self.elevator_id

        if employee_id != nil 
        json_payload = {
                        unique_external_id: "#{id}",
                        status: 2,            
                        priority: 1,
                        type: "Incident",
                        description: " An intervention is requested for the customer compagny #{Customer.find(customer_id).company_name} in the following field : <br>
                        -Battery number : #{battery_id} <br>
                        -Building number : #{building_id} <br>
                        -Column number : #{column_id} <br>
                        -Elevator number : #{elevator_id} <br>
                        The employee #{Employee.find(employee_id).first_name} #{Employee.find(employee_id).last_name} is assigned to the task. <br>
                        Report : <br>
                        #{report}<br> <br> <br> 
                        #{author.first_name} #{author.last_name}", 
                        subject: "Intervention ticket from #{author.first_name} #{author.last_name}"}.to_json
        end

        if employee_id == nil 
            json_payload = {
                            unique_external_id: "#{id}",
                            status: 2,            
                            priority: 1,
                            type: "Incident",
                            description: " An intervention is requested for the customer compagny #{Customer.find(customer_id).company_name} in the following field : <br>
                            -Battery number : #{battery_id} <br>
                            -Building number : #{building_id} <br>
                            -Column number : #{column_id} <br>
                            -Elevator number : #{elevator_id} <br>
                            There is no employee assigned to this intervention! <br>
                            Report : <br>
                            #{report}<br> <br> <br> 
                            #{author.first_name} #{author.last_name}" , 
                            subject: "Intervention ticket from #{author.first_name} #{author.last_name}"}.to_json
        end
                        
        freshdesk_api_path = 'api/v2/tickets'

        freshdesk_api_url  = "https://#{freshdesk_domain}.freshdesk.com/#{freshdesk_api_path}"

        site = RestClient::Resource.new(freshdesk_api_url, user_name_or_api_key, password_or_x)

        begin
        response = site.post(json_payload, :content_type=>'application/json')
        puts "response_code: #{response.code} \n Location Header: #{response.headers[:location]}\n response_body: #{response.body}"
        rescue RestClient::Exception => exception
        puts 'API Error: Your request is not successful. If you are not able to debug this error properly, mail us at support@freshdesk.com with the follwing X-Request-Id'
        puts "X-Request-Id : #{exception.response.headers[:x_request_id]}"
        puts "Response Code: #{exception.response.code} Response Body: #{exception.response.body} "
        end
    end
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  before_action :set_intervention, only: %i[ show edit update destroy ]

  # GET /interventions or /interventions.json
  def index
    @interventions = Intervention.all
  end

  # GET /interventions/1 or /interventions/1.json
  def show
  end

  # GET /interventions/new 
  def new
    if current_user.is_employee? 
      
      @intervention = Intervention.new
      @customers = Customer.all
      @buildings = Building.all
      @batteries = Battery.all
      @columns = Column.all
      @elevators = Elevator.all
      @employees = Employee.all   
    end
  end

  def update_buildings
    @buildings = Building.where("customer_id = ?", params[:customer_id])
    p @buildings
    respond_to do |format|
      format.json { render :json => @buildings}
      p @buildings
    end
  end

  def update_batteries
    @batteries = Battery.where("building_id = ?", params[:building_id])
    p @batteries
    respond_to do |format|
      format.json { render :json => @batteries}
    end
  end

  def update_columns
    @columns = Column.where("battery_id = ?", params[:battery_id])
    respond_to do |format|
      format.json { render :json => @columns}
    end
  end

  def update_elevators
    @elevators = Elevator.where("column_id = ?", params[:column_id])
    respond_to do |format|
      format.json { render :json => @elevators}
    end
  end

  # POST /interventions or /interventions.json
  def create
    @intervention = Intervention.new(intervention_params)

    @intervention.result = "Incomplete"
    @intervention.status = "Pending"
    @intervention.author = current_user.employee
    # if current_user.id == Employee.all.user_id
    #   @intervention.author 
    # end
    # @intervention.author = Employee.find(curent_user.id).
   
    # x= current_user.employee.id
    # p x
    # p x 
    # p x 
    # p x

 
    respond_to do |format|
      if @intervention.save
        format.html { redirect_to root_path, notice: "Intervention was successfully created." }
        format.json { render :show, status: :created, location: @intervention }
      else
        @customers = Customer.all
        @buildings = Building.all
        @batteries = Battery.all
        @columns = Column.all
        @elevators = Elevator.all
        @employees = Employee.all   
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interventions/1 or /interventions/1.json
  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to intervention_url(@intervention), notice: "Intervention was successfully updated." }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1 or /interventions/1.json
  def destroy
    @intervention.destroy

    respond_to do |format|
      format.html { redirect_to interventions_url, notice: "Intervention was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intervention_params
      params.require(:intervention).permit(:customer_id, :building_id, :battery_id, :column_id, :elevator_id, :employee_id, :start_date_and_time_of_the_intervention, :end_date_and_time_of_the_intervention, :result, :report, :status)
    end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<%= form_with(model: intervention) do |form| %>
  <% if intervention.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
        <% intervention.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



<div class="col-md-4"> 
   <div>
    <%= form.label :customer_id, "Customer *", class: "form-label" %>
    <%= form.select :customer_id,  options_for_select(@customers.collect { |customers| ["#{customers.company_name}   ID #  #{customers.id} ",customers.id] }), {selected: "", disabled: "", prompt: "--select a customer--"},   {id: 'customers_select', :required => true} %>
  </div>

  <div>
    <%= form.label :building_id, "Building *", class: "form-label" %>
    <%= form.select :building_id, options_for_select(@buildings.collect { |buildings| [buildings.id] }), {:prompt => "--fill other fields first--"}, {id: 'buildings_select', :required => true, disabled: true} %>
  </div>

  <div>
    <%= form.label :battery_id, "Battery *", style: "display: block" %>
    <%= form.select :battery_id, options_for_select(@batteries.collect { |batteries| [batteries.id] }), {:prompt => "--fill other fields first--"},  {id: 'batteries_select', :required => true, disabled: true,} %>
  </div>

  <div>
    <%= form.label :column_id, style: "display: block" %>
     <%= form.select :column_id, options_for_select(@columns.collect { |columns| [columns.id] }), {:prompt => "--fill other fields first--"}, { id: 'columns_select', disabled: true } %>
  </div>

  <div>
    <%= form.label :elevator_id, style: "display: block" %>
    <%= form.select :elevator_id, options_for_select(@elevators.collect { |elevators| [elevators.id] }), {:prompt => "--fill other fields first--"}, { id: 'elevators_select', disabled: true } %>
  </div>

  <div>
    <%= form.label :employee_id, style: "display: block" %>
     <%= form.select :employee_id, options_for_select(@employees.collect { |employees| ["#{employees.first_name}"+ "#{employees.last_name}" + " ID #" + "#{employees.id} ", employees.id]}), {:prompt => "--select your employee--"} %>
  </div>
  
  <div>
    <%= form.label :report, style: "display: block"%>
    <%= form.text_area :report, :rows=>6, :cols=>50 %>
  </div>

   <div>
    <%= form.submit %>
  </div>
</div>  

 
  <script>
  $('#customers_select').change(function() {
    $.ajax({
      
      url: 'interventions/update_buildings',
      type: 'GET',
      data: {
        customer_id: $("#customers_select option:selected").val()
      },
      success: function(buildings) {
        // Clear all options from course select
        $("select#buildings_select option").remove();
        $("select#batteries_select option").remove();
        $("select#columns_select option").remove();
        $("select#elevators_select option").remove();
        //put in a empty default line
        var row = "<option value=\"" + "" + "\" disabled selected hidden>" + "--select your building--" + "</option>";
        var unusableRow = ("<option value=\"" + "" + "\">" + "--fill other fields first--" + "</option>");
        $(row).appendTo("select#buildings_select");
        $(unusableRow).appendTo("select#batteries_select");
        $(unusableRow).appendTo("select#columns_select");
        $(unusableRow).appendTo("select#elevators_select");

        $('#batteries_select').prop('disabled',true);
        $('#columns_select').prop('disabled',true);
        $('#elevators_select').prop('disabled',true);
        
        // Fill course select
        $.each(buildings, function(i, building) {
            console.log(building)
            row = "<option value=\"" + building.id + "\">" + building.id + "</option>";
            $(row).appendTo("select#buildings_select");
        });
      $('#buildings_select').prop('disabled',false);
      }
    })
  })

  $('#buildings_select').change(function() {
    $.ajax({
      url: 'interventions/update_batteries',
      type: 'GET',
      data: {
        building_id: $("#buildings_select option:selected").val()
      },
      success: function(batteries) {
        console.log(batteries)
        // Clear all options from course select
        $("select#batteries_select option").remove();
        $("select#columns_select option").remove();
        $("select#elevators_select option").remove();
        //put in a empty default line
        var row = "<option value=\"" + "" + "\" disabled selected hidden>" + "--select your battery--" + "</option>";
        var unusableRow = ("<option value=\"" + "" + "\">" + "--fill other fields first--" + "</option>");
        $(row).appendTo("select#batteries_select");
        $(unusableRow).appendTo("select#columns_select");
        $(unusableRow).appendTo("select#elevators_select");
        
        $('#columns_select').prop('disabled',true);
        $('#elevators_select').prop('disabled',true);

        // Fill course select
        $.each(batteries, function(i, battery) {
            row = "<option value=\"" + battery.id + "\">" + battery.id + "</option>";
            $(row).appendTo("select#batteries_select");
        });
      $('#batteries_select').prop('disabled',false);  
      }
    })
  })

   $('#batteries_select').change(function() {
    $.ajax({
      url: 'interventions/update_columns',
      type: 'GET',
      data: {
        battery_id: $("#batteries_select option:selected").val()
      },
      success: function(columns) {
        // Clear all options from course select
        $("select#columns_select option").remove();
        $("select#elevators_select option").remove();
        //put in a empty default line
        var row = "<option value=\"" + "" + "\" disabled selected hidden>" + "--select your column--" + "</option>";
        var unusableRow = "<option value=\"" + "" + "\">" + "--fill other fields first--" + "</option>";
        
        $(row).appendTo("select#columns_select").disabled = true;
        $(unusableRow).appendTo("select#elevators_select");

        $('#elevators_select').prop('disabled',true);
      
        // Fill course select
        $.each(columns, function(i, column) {
            row = "<option value=\"" + column.id + "\">" + column.id + "</option>";
            $(row).appendTo("select#columns_select");
        });
      $('#columns_select').prop('disabled',false);  
      }
    })
  })

   $('#columns_select').change(function() {
    $.ajax({
      url: 'interventions/update_elevators',
      type: 'GET',
      data: {
        column_id: $("#columns_select option:selected").val()
      },
      success: function(elevators) {
        // Clear all options from course select
        $("select#elevators_select option").remove();
        //put in a empty default line
        var row = "<option value=\"" + "" + "\" disabled selected hidden>" + "--select your elevator--" + "</option>";
        $(row).appendTo("select#elevators_select");

        // Fill course select
        $.each(elevators, function(i, elevator) {
            row = "<option value=\"" + elevator.id + "\">" + elevator.id + "</option>";
            $(row).appendTo("select#elevators_select");
        });
      $('#elevators_select').prop('disabled',false);  
      }
    })
  })
  
  </script>  
<% end %>

app/views/interventions/_intervention.html.erb
<div id="<%= dom_id intervention %>">
  <p>
    <strong>Customer:</strong>
    <%= intervention.customer_id %>
  </p>

  <p>
    <strong>Building:</strong>
    <%= intervention.building_id %>
  </p>

  <p>
    <strong>Battery:</strong>
    <%= intervention.battery_id %>
  </p>

  <p>
    <strong>Column:</strong>
    <%= intervention.column_id %>
  </p>

  <p>
    <strong>Elevator:</strong>
    <%= intervention.elevator_id %>
  </p>

  <p>
    <strong>Employee:</strong>
    <%= intervention.employee_id %>
  </p>

  <p>
    <strong>Start date and time of the intervention:</strong>
    <%= intervention.start_date_and_time_of_the_intervention %>
  </p>

  <p>
    <strong>End date and time of the intervention:</strong>
    <%= intervention.end_date_and_time_of_the_intervention %>
  </p>

  <p>
    <strong>Result:</strong>
    <%= intervention.result %>
  </p>

  <p>
    <strong>Report:</strong>
    <%= intervention.report %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= intervention.status %>
  </p>

</div>

app/views/interventions/edit.html.erb
<h1>Editing intervention</h1>

<%= render "form", intervention: @intervention %>

<br>

<div>
  <%= link_to "Show this intervention", @intervention %> |
  <%= link_to "Back to interventions", interventions_path %>
</div>

app/views/interventions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Interventions</h1>

<div id="interventions">
  <% @interventions.each do |intervention| %>
    <%= render intervention %>
    <p>
      <%= link_to "Show this intervention", intervention %>
    </p>
  <% end %>
</div>

<%= link_to "New intervention", new_intervention_path %>

app/views/interventions/new.html.erb
<h1>New intervention</h1>

<%= render "form", intervention: @intervention %>

<br>

<div>
  <%= link_to "Back to interventions", interventions_path %>
</div>

app/views/interventions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @intervention %>

<div>
  <%= link_to "Edit this intervention", edit_intervention_path(@intervention) %> |
  <%= link_to "Back to interventions", interventions_path %>

  <%= button_to "Destroy this intervention", @intervention, method: :delete %>
</div>